"""Rename precision and add composite indexes

Revision ID: 6966f02e8f5b
Revises: f436ea22ac12
Create Date: 2026-07-04 17:20:17.471610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6966f02e8f5b'
down_revision: Union[str, None] = 'f436ea22ac12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
